### ISSUE TITLE
Context Error

### ISSUE THREAD

**Issue by imaginairehector** [masa-sumimoto/adobe-xd-color-scale#1]
Hi there, 

I can't use Color Scale due to an error I can't resolve. I've reinstalled the plugin but still no luck. My boss isn't having any issues with it. 

Any help would be useful, thanks
Hector

<img width="978" alt="Screenshot 2020-08-03 at 16 26 50" src="https://user-images.githubusercontent.com/69159170/89199206-23cac480-d5a6-11ea-8532-3ee55d7c188a.png">

**Comment by masa-sumimoto** [comment]
@imaginairehector 
Very Sorry for my late reply!
And thank you for using `Color Scale`! ^^

First please create an Artboard. Then place a node on it and run the plugin.

If your project does not have an artboard, you can create one from the menu.

![ss2](https://user-images.githubusercontent.com/27806318/89734861-b2a17a80-da99-11ea-8343-8f36abc30cc9.png)

I guessed the situation from your screenshot.
If the situation does not improve, please contactme again.

m(_ _)m
